### PR TITLE
Fix for #84 and and as it comes: auto building before testing for travis.

### PR DESCRIPTION
**Pull request by Kanaye**
After realzing that my first fix was overcomplicated and how easy it was is too fix this.
Also added a test for this bug :smile: .

### CODE REVIEW

**Comment by Kanaye** [comment]
Okay travis seems to get an other result then myself... let me take a look...

**Comment by astoilkov** [comment]
It runs the tests in Firefox. Maybe this is the reason.

**Comment by Kanaye** [comment]
i've been running in all browsers that ``grunt test`` runs and an old safari...

**Comment by Kanaye** [comment]
derp... Cause in my opinion it's your task to push a new build to the repo, I'm not pushing the build "blocks.js". Travis is just running npm test... So it's my own test failling...

**Comment by Kanaye** [comment]
[here](https://gist.githubusercontent.com/Kanaye/8dabd3609258bcf42119/raw/400e2d67da18fc4382633be7a4c88e946acea74d/jsblocks_npm_test_79ead66f0b9d7a776afec88b433ac0f80cef6be8.txt) the plain text version of ``npm test`` I'm getting runnig the tests with my latest build. But if you whish I can also push a version including the build.

Maybee travis should build a vesion before testing. Afaik Travis timeout is set to 50 minutes and i think building blocks on a raspberrypi is done in less time :smile:

**Comment by Kanaye** [comment]
Okay that last commit wasn't meant to be in this pull request :sweat_smile: but hey, I got travis to buld and then test. I can split this into two differtent pull requests or remove the travis stuff again if you wish.
As you see I can't stop trying to fix things until I fixed what I derped up or missed. Like the fact that travis is/was not builing jsblocks itself and therefore the tests of my previous pull requests wasn't correct.

**Comment by astoilkov** [comment]
Perfect. It should have been in different pull request but not a big deal. Merging it.

**Pull request merged**
