### PR TITLE
Updating/Insetring of wrong nodes fixed. Closes #104

### LINKED ISSUE #104: Blocks is inserting the wrong text in the wrong node
Blocks is ~~updating~~ inserting into the wrong text-node in an ``each`` data-query in the  ``reset()``- function  of array-observables, when these get reset the first time.
To be clear: http://jsfiddle.net/bpkvse3r/1/ click the reset button at least 3 times.
Will look into this this tomorrow.

[edit:]
Correcting myself: The update is on the right node. The initial insert is on the wrong one.

### PR DESCRIPTION
**Pull request by Kanaye**
For details read the message of the first commit :wink:.
If you find an edge case I didn't fix or you don't like something about this solution feel free to say.
Closes #104

### CODE REVIEW

**Comment by astoilkov** [comment]
I will take a look at the solution for this soon and will merge it.

**Comment by Kanaye** [comment]
I removed the ``[chunk of expression].nodePositions`` as it was originaly for an other way to implement this behavior and now isunnecessary for this implementation and just blew up the code.

Also just take your time to review the changes. The PR-might change over time (as it did now) but it won't run away :smile:.

**Comment by astoilkov** [comment]
Wow. Cool. We have a lot of more because we are launching [Caret](http://caret.io/). I will take a look in the next couple of days. This way you will also have time to make changes if you want. :)

**Comment by astoilkov** [comment]
I am ready to merge the pull request. Do you have any additional changes you want to add before that?

**Comment by Kanaye** [comment]
Great! No I have no additional changes.

**Pull request merged**
