### PR TITLE
Removed context.childs.

### LINKED ISSUE #111: Cannot set property '$this' of undefined.
Found in the shopping example.
Steps to reproduce:
* open the shopping-example
* click under "CATEGORIES" on "UNDERWEAR"
* click under "BRANDS" on "RACH"
* click under "CATEGORIES" on "ALL"

I have no time to spend on this today but I can look into this later this week.

### PR DESCRIPTION
**Pull request by Kanaye**
I think I tested enough.
I will think about the tests mentioned in #111 and open an P.R. once I have a clean implementation.
Resolves #111.

### CODE REVIEW

**Comment by astoilkov** [comment]
I think you have missed one place where the `._childs` property is used:
https://github.com/astoilkov/jsblocks/blob/c17f2627d422beb1a7f632d29fbafb9ff497247e/dist/query/blocks-query.js#L2662

**Comment by Kanaye** [comment]
Whoops. You're totally right. I think I removed it in my local repository and forgot to push it. I'll push it once I'm back at my workstation

**Comment by astoilkov** [comment]
Perfect.

**Comment by Kanaye** [comment]
Okay, maybe I should get a cup of coffee before I answer stuff on github in the morning :smile: .

My workstation branch and the one here on gihub have no difference. 

I also was curious how the tests passed cause I was sure they were failling when I worked on it.

The line you linked above is in the ``dist/query`` directory and because I'm not committing the built files (because I think the repositories dist folder should stay on the current release) so these are 'outdated'. Here the line in the source diff where I removed it: https://github.com/astoilkov/jsblocks/pull/140/files#diff-1750a8a6163be12789b27db2dc590968L520

**Comment by astoilkov** [comment]
Oops. Sorry. We both got confused here. :D Merging

**Pull request merged**
